"""Phase 5: platform tests for the observability generated by the current template.

The generated CLI and evaluator run in subprocesses with golden_path import-
blocked. The deterministic, in-process scenario tests (fake clock, fixed ids,
in-memory sink) live in the generated project's tests/test_telemetry.py; this
file checks the real command-line behavior. Only explicitly nondeterministic
fields (trace_id, start_time_unix_ns, duration_ms, latency.over_declared_max)
are normalized.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest
from jsonschema import Draft202012Validator

from conftest import only_record, stderr_records
from golden_path import scaffold

CAPABILITY = "observable-demo"
NONDETERMINISTIC = ("trace_id", "start_time_unix_ns", "duration_ms")
# The telemetry contract the CURRENT template snapshots (v2 from template 0.5.0).
TELEMETRY_SCHEMA = json.loads(scaffold.PLATFORM_FILES["platform/telemetry-record.schema.json"].read_text())


@pytest.fixture
def project(tmp_path) -> Path:
    destination, _ = scaffold.new_capability(CAPABILITY, tmp_path)
    return destination


def run_py(project: Path, env: dict, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, *args], cwd=project, env=env, capture_output=True, text=True, check=False
    )


def spans(stderr: str) -> list[dict]:
    return [r for r in stderr_records(stderr) if r["record"] == "span"]


def normalized(records: list[dict]) -> list[dict]:
    result = []
    for record in records:
        record = {k: v for k, v in record.items() if k not in NONDETERMINISTIC}
        record["attributes"] = {k: v for k, v in record["attributes"].items() if k != "latency.over_declared_max"}
        result.append(record)
    return result


def tree(root: Path) -> list[str]:
    return sorted(p.relative_to(root).as_posix() for p in root.rglob("*"))


# --- contracts -------------------------------------------------------------------------


@pytest.mark.parametrize("name", ["telemetry-record.schema.json", "pricing.schema.json"])
def test_canonical_schemas_are_valid_and_snapshotted_byte_for_byte(project, name):
    canonical = scaffold.PLATFORM_FILES[f"platform/{name}"]
    Draft202012Validator.check_schema(json.loads(canonical.read_text()))
    assert (project / "platform" / name).read_bytes() == canonical.read_bytes()


@pytest.mark.parametrize("filename", ["telemetry-record.schema.json", "telemetry-record.v2.schema.json"])
def test_telemetry_schemas_have_no_generic_attribute_map(filename):
    schema = json.loads((scaffold.LAB_ROOT / "schemas" / filename).read_text())
    text = json.dumps(schema)
    for escape_hatch in ('"metadata"', '"labels"', '"custom.attributes"'):
        assert escape_hatch not in text
    for defn in ("runAttributes", "modelRequestAttributes", "toolRequestAttributes"):
        if defn in schema["$defs"]:
            assert schema["$defs"][defn]["additionalProperties"] is False


def test_template_ships_with_no_prices(project):
    assert "prices: []" in (project / "pricing.yaml").read_text()


# --- capability CLI ------------------------------------------------------------------------


def test_cli_stdout_is_result_and_stderr_is_typed_valid_spans(project, blocked_env):
    completed = run_py(project, blocked_env, "src/capability.py", "fixtures/sample_input.json", "--correlation-id", "manual-phase5")
    assert completed.returncode == 0, completed.stderr
    result = json.loads(completed.stdout)
    assert set(result) == {"capability", "model", "model_requests", "output"}  # no telemetry in the result
    records = stderr_records(completed.stderr)
    assert [r["record"] for r in records] == ["span", "span"]
    for record in records:
        assert list(Draft202012Validator(TELEMETRY_SCHEMA).iter_errors(record)) == []
        assert record["correlation_id"] == "manual-phase5"
    root = next(r for r in records if r["name"] == "capability.run")
    assert root["attributes"]["usage.status"] == "unknown"
    assert root["attributes"]["usage.input_tokens"] is None  # unknown, NOT 0
    assert root["attributes"]["cost.unknown_reason"] == "no_pricing"


def test_fixture_payload_never_appears_in_telemetry(project, blocked_env):
    fixture = json.loads((project / "fixtures" / "sample_input.json").read_text())
    completed = run_py(project, blocked_env, "src/capability.py", "fixtures/sample_input.json")
    output = json.loads(completed.stdout)["output"]
    sensitive = [fixture["title"], fixture["summary"], *fixture["files_changed"], output["headline"], output["explanation"]]
    for value in sensitive:
        assert value not in completed.stderr


def test_cli_telemetry_is_deterministic_after_normalizing_time_and_trace(project, blocked_env):
    runs = [
        run_py(project, blocked_env, "src/capability.py", "fixtures/sample_input.json", "--correlation-id", "same")
        for _ in range(2)
    ]
    assert runs[0].stdout == runs[1].stdout
    first, second = (spans(r.stderr) for r in runs)
    assert first[0]["trace_id"] != second[0]["trace_id"]  # trace ids really differ ...
    assert normalized(first) == normalized(second)  # ... and nothing else does


def test_invalid_input_cli_records_known_zero(project, blocked_env, tmp_path):
    bad = tmp_path / "bad.json"
    fixture = json.loads((project / "fixtures" / "sample_input.json").read_text())
    bad.write_text(json.dumps({**fixture, "change_id": "SENSITIVE-ID-MARKER"}))
    completed = run_py(project, blocked_env, "src/capability.py", str(bad))
    assert completed.returncode == 2
    assert completed.stdout == ""
    assert "SENSITIVE-ID-MARKER" not in completed.stderr
    [root] = spans(completed.stderr)
    assert root["status"] == "error"
    assert root["attributes"]["model_requests.used"] == 0
    assert root["attributes"]["usage.status"] == "no_requests"
    assert (root["attributes"]["usage.input_tokens"], root["attributes"]["usage.output_tokens"]) == (0, 0)
    assert root["attributes"]["cost.status"] == "no_requests"
    assert only_record(completed.stderr, "error")["error"] == "InputValidationError"


def test_telemetry_file_is_explicit_and_default_creates_no_files(project, blocked_env, tmp_path):
    before = tree(project)
    default = run_py(project, blocked_env, "src/capability.py", "fixtures/sample_input.json")
    assert tree(project) == before  # no implicit telemetry file

    target = tmp_path / "telemetry.jsonl"
    to_file = run_py(project, blocked_env, "src/capability.py", "fixtures/sample_input.json", "--telemetry-file", str(target))
    assert to_file.returncode == 0
    assert to_file.stdout == default.stdout
    assert to_file.stderr == ""  # spans went to the file, not stderr
    assert [json.loads(line)["record"] for line in target.read_text().splitlines()] == ["span", "span"]


def test_unwritable_telemetry_file_refuses_to_run(project, blocked_env, tmp_path):
    completed = run_py(project, blocked_env, "src/capability.py", "fixtures/sample_input.json", "--telemetry-file", str(tmp_path))
    assert completed.returncode == 5
    assert completed.stdout == ""
    assert only_record(completed.stderr, "error")["error"] == "TelemetryDeliveryError"


@pytest.mark.parametrize("bad", ["has space", "semi;colon"])
def test_invalid_correlation_id_is_a_usage_error(project, blocked_env, bad):
    completed = run_py(project, blocked_env, "src/capability.py", "fixtures/sample_input.json", "--correlation-id", bad)
    assert completed.returncode == 2
    assert completed.stdout == ""


# --- evaluator ------------------------------------------------------------------------------


def test_eval_report_stays_byte_identical_while_telemetry_differs(project, blocked_env):
    first = run_py(project, blocked_env, "evals/evaluator.py", "--correlation-id", "eval-run-a")
    second = run_py(project, blocked_env, "evals/evaluator.py", "--correlation-id", "eval-run-b")
    assert first.returncode == second.returncode == 0
    assert first.stdout == second.stdout
    assert first.stderr != second.stderr
    for completed, run_id in ((first, "eval-run-a"), (second, "eval-run-b")):
        roots = [s for s in spans(completed.stderr) if s["name"] == "capability.run"]
        report = json.loads(completed.stdout)
        assert [r["attributes"]["eval.case_id"] for r in roots] == [c["id"] for c in report["cases"]]
        assert {r["attributes"]["eval.suite_sha256"] for r in roots} == {report["suite"]["sha256"]}
        assert {r["attributes"]["eval.run_id"] for r in roots} == {run_id}
        assert only_record(completed.stderr, "eval_summary")["eval.run_id"] == run_id
    for key in ("eval-run-a", "trace_id", "duration_ms", "usage", "cost"):
        assert key not in first.stdout


def test_eval_stderr_is_only_typed_records(project, blocked_env):
    completed = run_py(project, blocked_env, "evals/evaluator.py")
    records = stderr_records(completed.stderr)  # raises if any line is not JSON
    assert {r["record"] for r in records} == {"span", "eval_summary"}
    scripted = [
        r for r in records
        if r["record"] == "span" and r["name"] == "capability.run" and r["attributes"]["eval.adapter_source"] == "scripted"
    ]
    assert [r["attributes"]["eval.case_id"] for r in scripted] == ["reject-malformed-model-output"]
