"""Phase 3: platform tests for the runtime generated by capability@0.2.0.

The generated project is exercised only in subprocesses. Its module names
(`capability`, `contracts`) must not share sys.modules with the platform, and
a subprocess is the honest way to prove it runs without `golden_path`.

The detailed runtime-boundary proofs (invalid input never reaches the model,
invalid output is rejected, the request budget is never exceeded) live in the
generated project's own tests/test_capability.py, which is product-team-owned.
This file runs that suite and adds platform-level checks around it.
"""

from __future__ import annotations

import ast
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest
import yaml
from jsonschema import Draft202012Validator

from golden_path import scaffold

CAPABILITY = "runtime-demo"
GENERATED_MODULES = {"capability", "contracts", "model_adapter", "evaluator"}
ALLOWED_THIRD_PARTY = {"jsonschema", "yaml", "pytest"}
FORBIDDEN_IN_SRC = {
    "golden_path",
    "os",
    "socket",
    "ssl",
    "http",
    "urllib",
    "subprocess",
    "requests",
    "httpx",
    "aiohttp",
    "openai",
    "anthropic",
}


@pytest.fixture(scope="module")
def project(tmp_path_factory) -> Path:
    parent = tmp_path_factory.mktemp("generated")
    destination, _ = scaffold.new_capability(CAPABILITY, parent)
    return destination


def run_cli(project: Path, env: dict, input_path: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "src/capability.py", input_path],
        cwd=project,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )


def test_block_stub_really_blocks_golden_path(blocked_env):
    completed = subprocess.run(
        [sys.executable, "-c", "import golden_path"], env=blocked_env, capture_output=True, text=True
    )
    assert completed.returncode != 0
    assert "must not import golden_path" in completed.stderr


# --- generation --------------------------------------------------------------------


def test_manifest_records_current_template_and_fake_adapter(project):
    manifest = yaml.safe_load((project / "capability.yaml").read_text())
    assert manifest["metadata"]["template_version"] == scaffold.TEMPLATE_VERSION
    assert manifest["spec"]["model"]["adapter"] == "fake"


def test_contract_snapshot_is_byte_identical_to_canonical_schema(project):
    snapshot = (project / "platform" / "capability.schema.json").read_bytes()
    assert snapshot == scaffold.CAPABILITY_SCHEMA_PATH.read_bytes()


def test_template_cannot_shadow_platform_files(tmp_path, monkeypatch):
    root = tmp_path / "templates"
    template = root / scaffold.TEMPLATE_ID / scaffold.TEMPLATE_VERSION
    template.parent.mkdir(parents=True)
    shutil.copytree(scaffold.template_dir(), template)
    (template / "platform").mkdir()
    (template / "platform" / "capability.schema.json").write_text("{}")
    monkeypatch.setattr(scaffold, "TEMPLATES_ROOT", root)
    with pytest.raises(scaffold.TemplateContractError, match="platform-managed"):
        scaffold.render(CAPABILITY)


# --- independence and static boundaries ----------------------------------------------


def _imports(path: Path) -> set[str]:
    names = set()
    for node in ast.walk(ast.parse(path.read_text(), filename=str(path))):
        if isinstance(node, ast.Import):
            names |= {alias.name.split(".")[0] for alias in node.names}
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            names.add(node.module.split(".")[0])
    return names


def test_generated_code_imports_only_stdlib_declared_deps_and_itself(project):
    allowed = set(sys.stdlib_module_names) | ALLOWED_THIRD_PARTY | GENERATED_MODULES
    for path in sorted(project.rglob("*.py")):
        unexpected = _imports(path) - allowed
        assert not unexpected, f"{path.relative_to(project)} imports {sorted(unexpected)}"
        assert "golden_path" not in _imports(path)


def test_generated_src_has_no_network_env_or_provider_access(project):
    for path in sorted([*(project / "src").glob("*.py"), *(project / "evals").glob("*.py")]):
        forbidden = _imports(path) & FORBIDDEN_IN_SRC
        assert not forbidden, f"{path.name} imports {sorted(forbidden)}"
        text = path.read_text()
        assert "environ" not in text and "getenv" not in text, path.name
        assert "importlib" not in text and "__import__" not in text, path.name


def test_generated_requirements_cover_third_party_imports(project):
    requirements = (project / "requirements.txt").read_text().lower()
    for name in ("jsonschema", "pyyaml", "pytest"):
        assert name in requirements


# --- generated suite and command line, with golden_path blocked -------------------------


def test_generated_test_suite_passes_without_golden_path(project, blocked_env):
    completed = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider"],
        cwd=project,
        env=blocked_env,
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 0, completed.stdout + completed.stderr
    assert " passed" in completed.stdout and "failed" not in completed.stdout


def test_cli_sample_run_produces_schema_valid_deterministic_result(project, blocked_env):
    first = run_cli(project, blocked_env, "fixtures/sample_input.json")
    second = run_cli(project, blocked_env, "fixtures/sample_input.json")
    assert first.returncode == 0, first.stderr
    assert first.stdout == second.stdout
    result = json.loads(first.stdout)
    output_schema = json.loads((project / "schemas" / "output.schema.json").read_text())
    assert list(Draft202012Validator(output_schema).iter_errors(result["output"])) == []
    assert result["capability"] == {
        "name": CAPABILITY,
        "version": "0.1.0",
        "template_version": scaffold.TEMPLATE_VERSION,
    }
    assert result["model"] == {
        "declared_adapter": "fake",
        "declared_profile": "balanced",
        "adapter_reported": {"adapter": "fake", "model": "fake-deterministic-v2"},
    }
    assert result["model_requests"] == {"used": 1, "limit": 2}


def test_cli_invalid_input_exits_2_without_result_or_echo(project, blocked_env, tmp_path):
    marker = "SENSITIVE-CLI-MARKER"
    bad = tmp_path / "bad.json"
    sample = json.loads((project / "fixtures" / "sample_input.json").read_text())
    bad.write_text(json.dumps({**sample, "change_id": marker}))
    completed = run_cli(project, blocked_env, str(bad))
    assert completed.returncode == 2
    assert completed.stdout == ""
    assert marker not in completed.stderr
    error = json.loads(completed.stderr)
    assert error["error"] == "InputValidationError"
    assert error["model_requests_used"] == 0


def test_cli_malformed_json_exits_2(project, blocked_env, tmp_path):
    bad = tmp_path / "bad.json"
    bad.write_text("{not json")
    completed = run_cli(project, blocked_env, str(bad))
    assert completed.returncode == 2
    assert completed.stdout == ""


@pytest.mark.parametrize(
    ("original", "replacement", "expected"),
    [
        ("tools: []", "tools: [search_docs]", "no tool runtime"),
        ("adapter: fake", "adapter: some-provider", "unknown adapter"),
        ("max_model_requests: 2", "max_model_requests: 0", "violates platform/capability.schema.json"),
        ("adapter: fake", "adapter: fake\n    api_key: redacted", "violates platform/capability.schema.json"),
    ],
    ids=["tools-declared", "unknown-adapter", "zero-budget", "credential-in-manifest"],
)
def test_cli_invalid_manifest_exits_3_before_model(tmp_path, blocked_env, original, replacement, expected):
    destination, _ = scaffold.new_capability(CAPABILITY, tmp_path)
    manifest = destination / "capability.yaml"
    text = manifest.read_text()
    assert original in text
    manifest.write_text(text.replace(original, replacement, 1))
    completed = run_cli(destination, blocked_env, "fixtures/sample_input.json")
    assert completed.returncode == 3, completed.stderr
    assert completed.stdout == ""
    error = json.loads(completed.stderr)
    assert expected in error["message"]
    assert error["model_requests_used"] == 0
