"use client";

import { useState, type FormEvent } from "react";
import type { BriefResponse } from "@/lib/schemas/change-brief";

// Everything shown here is rendered as React text nodes. No server or PR
// content is ever injected as HTML.
//
// Phase 3 view: the validated ChangeBrief. It is always labelled AI-generated,
// and truncation and uncertainty are always shown. Phase 7 polishes the UX.

type ErrorResult = {
  status: "error";
  error: { category: string; message: string };
};

type ViewState =
  | { kind: "idle" }
  | { kind: "loading" }
  | { kind: "brief"; result: BriefResponse }
  | { kind: "error"; category: string; message: string };

export function AnalyzeForm() {
  const [url, setUrl] = useState("");
  const [view, setView] = useState<ViewState>({ kind: "idle" });

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setView({ kind: "loading" });
    try {
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url }),
      });
      const data = (await res.json()) as BriefResponse | ErrorResult;
      if (data.status === "brief") {
        setView({ kind: "brief", result: data });
      } else {
        setView({ kind: "error", category: data.error.category, message: data.error.message });
      }
    } catch {
      setView({ kind: "error", category: "internal_error", message: "The request failed." });
    }
  }

  return (
    <div className="flex w-full flex-col gap-6">
      <form onSubmit={onSubmit} className="flex flex-col gap-3 sm:flex-row">
        <label htmlFor="pr-url" className="sr-only">
          GitHub pull request URL
        </label>
        <input
          id="pr-url"
          name="url"
          type="text"
          inputMode="url"
          autoComplete="off"
          spellCheck={false}
          required
          maxLength={2048}
          placeholder="https://github.com/owner/repo/pull/123"
          value={url}
          onChange={(e) => setUrl(e.target.value)}
          className="flex-1 rounded-md border border-zinc-300 bg-white px-3 py-2 font-mono text-sm dark:border-zinc-700 dark:bg-zinc-900"
        />
        <button
          type="submit"
          disabled={view.kind === "loading"}
          className="rounded-md bg-zinc-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50 dark:bg-zinc-100 dark:text-zinc-900"
        >
          {view.kind === "loading" ? "Analyzing…" : "Explain PR"}
        </button>
      </form>

      <div aria-live="polite">
        {view.kind === "brief" && <BriefView result={view.result} />}
        {view.kind === "error" && (
          <p role="alert" className="text-sm text-red-700 dark:text-red-400">
            {view.message}
          </p>
        )}
      </div>
    </div>
  );
}

function List({ title, items }: { title: string; items: readonly string[] }) {
  return (
    <section className="flex flex-col gap-1">
      <h3 className="font-medium">{title}</h3>
      {items.length === 0 ? (
        <p className="text-zinc-500">Nothing supported by the evidence.</p>
      ) : (
        <ul className="list-disc pl-5">
          {items.map((text, i) => (
            <li key={i}>{text}</li>
          ))}
        </ul>
      )}
    </section>
  );
}

function fmt(n: number | null): string {
  return n === null ? "unknown" : String(n);
}

function BriefView({ result }: { result: BriefResponse }) {
  const b = result.brief;
  const m = b.brief;
  return (
    <div className="flex flex-col gap-4 text-sm">
      <p className="rounded-md border border-amber-300 bg-amber-50 px-3 py-2 text-amber-900 dark:border-amber-700 dark:bg-amber-950 dark:text-amber-200">
        AI-generated by {b.model}. It may be wrong; check it against the pull request.
      </p>
      {b.truncated && (
        <section className="rounded-md border border-zinc-300 px-3 py-2 dark:border-zinc-700">
          <p className="font-medium">
            Partial evidence: {b.files_considered} of {b.files_total} files were considered.
          </p>
          <ul className="list-disc pl-5 text-zinc-600 dark:text-zinc-400">
            {b.truncation_limitations.map((text, i) => (
              <li key={i}>{text}</li>
            ))}
          </ul>
        </section>
      )}
      <p className="font-mono text-xs text-zinc-500">
        {b.pr.owner}/{b.pr.repo}#{b.pr.number}
      </p>
      <section className="flex flex-col gap-1">
        <h3 className="font-medium">Summary</h3>
        <p>{m.summary}</p>
      </section>
      <section className="flex flex-col gap-1">
        <h3 className="font-medium">Why it matters</h3>
        <p>{m.why_it_matters}</p>
      </section>
      <section className="flex flex-col gap-1">
        <h3 className="font-medium">Change risk: {m.risk.level}</h3>
        <List title="Based on" items={m.risk.evidence} />
        <List title="Uncertainty" items={m.risk.uncertainty} />
      </section>
      <List title="User and business impact" items={m.user_impact} />
      <List title="Technical impact" items={m.technical_impact} />
      <List title="Testing signals in the PR" items={m.testing_signals} />
      <List title="Rollout" items={m.rollout_considerations} />
      <List title="Rollback" items={m.rollback_considerations} />
      <List title="Open questions" items={m.open_questions} />
      <List title="Limitations" items={m.limitations} />
      <p className="font-mono text-xs text-zinc-500">
        schema {b.schema_version} · prompt {b.prompt_version} · tokens in {fmt(b.usage?.input_tokens ?? null)} (cached{" "}
        {fmt(b.usage?.cached_input_tokens ?? null)}) · out {fmt(b.usage?.output_tokens ?? null)} (reasoning{" "}
        {fmt(b.usage?.reasoning_tokens ?? null)}) · cost {b.estimated_cost === null ? "unknown" : `~$${b.estimated_cost.usd}`}
      </p>
    </div>
  );
}
